

import java.util.TreeSet;


/**
 *
 * @author Jon_kevin27
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private TreeSet <String>listaProductos= new TreeSet<>();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Administración = new javax.swing.JMenu();
        jMenuItem_gestiondeproductos = new javax.swing.JMenuItem();
        jM_Consultas = new javax.swing.JMenu();
        jMenuItem_consultapornombre = new javax.swing.JMenuItem();
        jMenuItem_consutaporprecio = new javax.swing.JMenuItem();
        jMenuItem_consultaporrubro = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP6 De Todo S.A.");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        jM_Administración.setText("Administración");

        jMenuItem_gestiondeproductos.setText("Gestión de Productos");
        jMenuItem_gestiondeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestiondeproductosActionPerformed(evt);
            }
        });
        jM_Administración.add(jMenuItem_gestiondeproductos);

        jMenuBar1.add(jM_Administración);

        jM_Consultas.setText("Consultas");

        jMenuItem_consultapornombre.setText("Consuta por nombre");
        jM_Consultas.add(jMenuItem_consultapornombre);

        jMenuItem_consutaporprecio.setText("Consulta por precio");
        jMenuItem_consutaporprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_consutaporprecioActionPerformed(evt);
            }
        });
        jM_Consultas.add(jMenuItem_consutaporprecio);

        jMenuItem_consultaporrubro.setText("Consulta por Rubro");
        jM_Consultas.add(jMenuItem_consultaporrubro);

        jMenuBar1.add(jM_Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_gestiondeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestiondeproductosActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Gestión_de_Productos formgestion = new Gestión_de_Productos(listaProductos);
        formgestion.setVisible(true);
        jDesktopPane1.add(formgestion);
        

    }//GEN-LAST:event_jMenuItem_gestiondeproductosActionPerformed

    private void jMenuItem_consutaporprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_consutaporprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_consutaporprecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jM_Administración;
    private javax.swing.JMenu jM_Consultas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_consultapornombre;
    private javax.swing.JMenuItem jMenuItem_consultaporrubro;
    private javax.swing.JMenuItem jMenuItem_consutaporprecio;
    private javax.swing.JMenuItem jMenuItem_gestiondeproductos;
    // End of variables declaration//GEN-END:variables
}
